<div id="<?php echo $this->id; ?>" class="steps-content">

    <?php
        $form = $this->step6Form;
        echo $this->form()->openTag($form);
    ?>

    <div class="row">
        <div class="col-sm-12">
            <h3><?php echo $this->translate('tr_melistoolcreator_custom_translations_title') ?></h3>
            <p><?php echo $this->translate('tr_melistoolcreator_custom_translations_desc') ?></p>
        </div>
        <div class="col-sm-12">
        <?php 
            $fieldTypeTable = clone $form->get('tcf-tool-table-type');

            echo($this->formElement($fieldTypeTable));
        ?>
        </div>

        <div class="col-sm-12">
            <?php if ($this->langTblCols) { ?>
                <h4><?php echo $this->translate('tr_melistoolcreator_pri_tbl_cols') ?></h4>
            <?php } ?>
            <div class="melis-toolcreator-steps-tbl-cols">
                <div class="widget-body list table-responsive">
                    <table class="table table-striped table-primary">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><?php echo $this->translate('tr_melistoolcreator_col_pk') ?></th>
                                <th><?php echo $this->translate('tr_melistoolcreator_col_name') ?></th>
                                <th><?php echo $this->translate('tr_melistoolcreator_col_type') ?></th>
                                <th class="text-center"><?php echo $this->translate('tr_melistoolcreator_col_validators') ?></th>
                                <th class="text-center"><?php echo $this->translate('tr_melistoolcreator_col_filters') ?></th>
                            </tr>
                        </thead>
                        <?php
                            $ctr = 1;
                            foreach ($this->tableCols As $tableColsKey => $col){

                                // Excluding field with Blob type
                                if (!is_bool(strpos($col['Type'], 'blob')))
                                    continue;

                                $fieldValidators = clone $form->get('tcf-db-table-col-validator');
                                $fieldFilters = clone $form->get('tcf-db-table-col-filter');
                                $fieldValidators->setName('tcf-db-table-col-validator'.$tableColsKey);

                                $pk = in_array($col['Key'], ['PRI']) ? ' <i class="fa fa-key fa-lg fa-rotate-90"></i>': '';
                                if (isset($col['isAutoIncrement'])){
                                    $fieldValidators->setAttribute('class', 'hidden');
                                    $fieldFilters->setAttribute('class', 'hidden');
                                }
                                if(isset($col['editableIsChecked']) && !$col['editableIsChecked']){
                                    $fieldValidators->setAttribute('class', 'hidden');
                                }
                                if(in_array(strtolower($col['Type']), ['date', 'datetime', 'timestamp', 'time'])){
                                    $fieldFilters->unsetValueOption('select');
                                    $fieldFilters->unsetValueOption('input');
                                }
                                
                                if(isset($col['ValidatorType']) && !is_null($col['ValidatorType'])){
                                    $fieldValidators->setValue($col['ValidatorType']);
                                }
                                if(isset($col['filterType']) && !is_null($col['filterType'])){
                                    $fieldFilters->setValue($col['filterType']);
                                }
                                
                                if (!is_bool(strpos($col['Type'], 'enum'))){
                                    $fieldValidators = $form->get('tcf-db-table-col-validator');
                                    $fieldFilters =  $form->get('tcf-db-table-col-filter');
                                }
                                if($fieldValidators->getAttribute('class') != 'hidden') {
                                    $slct2Id = 'selec2-'.uniqid();
                                    $attrib = $fieldValidators->getAttributes();
                                    $fieldValidators->setAttribute('data-slct2-id', $slct2Id);
                                    $formfieldValidators = '<div class="form-group">
                                                    '.$this->formElement($fieldValidators).'
                                                    </div>';
                                    $formfieldValidators .= '<script type="text/javascript">';
                                    $formfieldValidators .= '$("select[data-slct2-id=\''.$slct2Id.'\']").select2();';
                                    $formfieldValidators .= '$("select[data-slct2-id=\''.$slct2Id.'\']").next("span").css("width", "100%");';
                                    $formfieldValidators .= '</script>'; 
                                }else{
                                    $formfieldValidators = '';
                                }
                                echo '<tr>
                                        <td>'.$ctr++.'</td>
                                        <td>'.$pk.'</td>
                                        <td><b>'.$col['Field'].'</b></td>
                                        <td>'.$col['Type'].'</td>
                                        <td class="text-center">
                                            '.($formfieldValidators).'
                                        </td>
                                        <td class="text-center">
                                            '.$this->formElement($fieldFilters).'
                                        </td>
                                    </tr>';
                            }
                        ?>
                    </table>
                </div>
            </div>
        </div>

        <?php if ($this->langTblCols) { ?>
            <div class="col-sm-12">
                <h4><?php echo $this->translate('tr_melistoolcreator_lang_tbl_cols') ?></h4>
                <div class="melis-toolcreator-steps-tbl-cols">
                    <div class="widget-body list table-responsive">
                        <table class="table table-striped table-primary">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th><?php echo $this->translate('tr_melistoolcreator_col_pk') ?></th>
                                    <th><?php echo $this->translate('tr_melistoolcreator_col_name') ?></th>
                                    <th><?php echo $this->translate('tr_melistoolcreator_col_type') ?></th>
                                    <th class="text-center"><?php echo $this->translate('tr_melistoolcreator_col_field_type') ?></th>
                                    <th class="text-center"><?php echo $this->translate('tr_melistoolcreator_col_validators') ?></th>
                                </tr>
                            </thead>
                            <?php
                                $ctr = 1;
                                foreach ($this->langTblCols As $langTblColsKey => $col){

                                    // Excluding field with Blob type
                                    if (!is_bool(strpos($col['Type'], 'blob')))
                                        continue;

                                    // Adding prefix "tclangtblcol_" for language columns
                                    $langCOls = 'tclangtblcol_'.$col['Field'];

                                    $fieldValidators = clone $form->get('tcf-db-table-col-validator');
                                    $fieldFilters =  clone $form->get('tcf-db-table-col-filter');
                                    $fieldValidators->setName('tcf-db-table-col-validator'.$langTblColsKey);

                                    $pk = in_array($col['Key'], array('PRI')) ? ' <i class="fa fa-key fa-lg fa-rotate-90"></i>': '';

                                    $editableIcon = $col['editable'];
                                    $requiredIcon = $col['required'];

                                        
                                    if (!is_null($col['fieldValidators']))
                                        $fieldValidators->setValue($col['fieldValidators']);
                                    else{
                                        if (!$col['editableIsChecked'])
                                            $fieldValidators->setAttribute('disabled', 'disabled');

                                        foreach ($this->inputTypes As $type => $types)
                                            if (in_array(preg_replace("/\([^)]+\)/", '', $col['Type']), $types))
                                                $fieldValidators->setValue($type);
                                    }
                                    if(isset($col['editableIsChecked']) && !$col['editableIsChecked']){
                                        $fieldValidators->setAttribute('class', 'hidden');
                                    }
                                    $fk = null;
                                    if ($editableIcon === 'AUTO_INCREMENT'){
                                        $fieldValidators->setAttribute('class', 'hidden');
                                    }elseif ($editableIcon === 'FK'){
                                        $fk = '<i class="fa fa-key fa-lg fa-rotate-90 fa-key-fk"></i>';
                                        $fieldValidators->setAttribute('class', 'hidden');
                                    }

                                    if (isset($col['isAutoIncrement']))
                                        $fieldValidators->setAttribute('class', 'hidden');

                                    if (!is_bool(strpos($col['Type'], 'enum'))){
                                        $form->add([
                                            'name' => 'tcf-db-table-col-type',
                                            'type' => 'MelisText',
                                            'attributes' => [
                                                'value' => 'Select',
                                                'readonly' => 'readonly',
                                            ]
                                        ]);

                                        $fieldValidators = $form->get('tcf-db-table-col-validator');
                                        $fieldFilters = $form->get('tcf-db-table-col-filter');

                                    }

                                    echo '<tr>
                                            <td>'.$ctr++.'</td>
                                            <td>'.$pk.'</td>
                                            <td>'.$fk.'</td>
                                            <td><b>'.$col['Field'].'</b></td>
                                            <td>'.$col['Type'].'</td>
                                            <td class="text-center">
                                            '.$this->formElement($fieldValidators).'
                                            </td>
                                            <td class="text-center">
                                            '.$this->formElement($fieldFilters).'
                                            </td>
                                        </tr>';
                                }
                            ?>
                        </table>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>

    <?php
        echo $this->form()->closeTag();
    ?>

    <button class="btn btn-default btn-steps" data-curstep="6" data-nxtstep="5"><?php echo $this->translate('tr_melistoolcreator_back') ?></button>
    <button class="btn btn-default float-right btn-steps tcf-validate" data-curstep="6" data-nxtstep="7"><?php echo $this->translate('tr_melistoolcreator_next') ?></button>
</div>
